### ISSUE TITLE
There is issue in the example in the site it does not works

### ISSUE THREAD

**Issue by divyakumarjain** [formly-js/ng2.angular-formly.com#2]
https://plnkr.co/edit/x4ev1QmJ8gm7USGsJdMQ?p=preview

I can see following error in above example

SyntaxError: invalid property idconfig.js:1:1892
Error: (SystemJS) patchProperty/desc.set/wrapFn@https://unpkg.com/zone.js/dist/zone.js:698:26
    ZoneDelegate.prototype.invokeTask@https://unpkg.com/zone.js/dist/zone.js:265:21
    Zone.prototype.runTask@https://unpkg.com/zone.js/dist/zone.js:154:28
    ZoneTask/this.invoke@https://unpkg.com/zone.js/dist/zone.js:335:28

```
Error loading https://run.plnkr.co/6rUgOPY25aADrayS/app
```

**Comment by mohammedzamakhan** [comment]
Its running fine on my end.
